CREATE TABLE job (
    job_id VARCHAR(255) NOT NULL PRIMARY KEY,
    job_name VARCHAR(255) NOT NULL,
    job_config JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL);