package com.yubi.uls.bulk.core.dto;
public enum ConfigParams {
    JOB_ID, JOB_NAME, FILE_PATH, PARTITION_FILE_PATH, PARTITION, PARTITION_ACTIVITY_QUEUE, PARTITION_SIZE, PARTITION_GROUP,  MAX_CONCURRENCY, CHUNK_SIZE, READER_ACTIVITY_QUEUE, WRITER_ACTIVITY_QUEUE;
}
